name: "run tests"
on: push

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:4.0.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Project
        run: timeout 10s godot -e --headless || true
      - name: Run tests
        run: godot --headless --path "$PWD" -d -s addons/gut/gut_cmdln.gd -gdir=res://tests/ -gprefix=test_ -gsuffix=.gd -gexit -ginclude_subdirs
